menu/urls.py
from django.urls import path
from . import views
# from .middlewares.auth import auth_middleware


app_name = 'menu'
urlpatterns = [
    path('', views.signup, name='signup'),
    path('menu/', views.menu_list, name='menu_list'),
    path('<int:id>/<slug:menu_slug>/',
         views.food_items_details, name='food_items_details'),
    path('cart/', views.cart, name='cart'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('checkout/', views.checkout, name='checkout'),
    ]

tabletap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls', namespace='menu')),
    path('kitchen/', include('kitchen.urls', namespace='kitchen')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

menu/models.py
from django.db import models
from django.urls import reverse


class Menu(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='food_images/%Y/%m/%d', blank=True)

    '''
    class meta method dispaly image on menu page order by name.
    '''
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menu:food_list_by_category',
                       kwargs={'id': self.id, 'menu_slug': self.slug})


class FoodItem(models.Model):
    category = models.ForeignKey(Menu,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='food_images/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name
# Table created to store user details along with food details


class UserDetails(models.Model):
    user_email = models.CharField(max_length=100,
                                  default=None,
                                  blank=True, null=True)
    contact_number = models.CharField(max_length=10,
                                      default=None,
                                      blank=True,
                                      null=True)
    table_number = models.IntegerField(default=None, blank=True, null=True)
    food_details = models.CharField(max_length=500,
                                    default=None,
                                    blank=True,
                                    null=True)
    total_price = models.DecimalField(max_digits=10,
                                      decimal_places=2,
                                      default=None,
                                      blank=True,
                                      null=True)
    food_status = models.CharField(max_length=100,
                                   default=None,
                                   blank=True,
                                   null=True)
    serv_status = models.CharField(max_length=100,
                                   default=None,
                                   blank=True,
                                   null=True)
    created = models.DateTimeField()
    updated = models.DateTimeField()

menu/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Menu, FoodItem, UserDetails
import re
from django.contrib import messages
from django.db.models import Q
from .update import cart_quantity, fetch_date_time
import logging
import os
# import requests as r
# import json


def signup(request):
    """
    Args:
        email (string): Enter email.
        contact number (string): Enter contact number.

    Returns:
        if enter email and contact number valid:
            it will render to menu page
        else:
            reverse to signup page.
    """

    # To delete any session refer below syntax
    # del request.session['session_name']
    # request.session.save()

    fect_path = os.path.normpath(os.getcwd())
    log_path = f"{fect_path}\\logs\\TableTap.log"
    logging.basicConfig(
        filename=log_path,
        level=logging.INFO,
        format='%(filename)s:%(lineno)d - '
               '%(asctime)s - %(levelname)s - %(message)s')

    logging.info("Signup page")

    if 'cart' not in request.session:
        request.session['cart'] = {}
        logging.info("cart session created")

    if 'wish_list' not in request.session:
        request.session['wish_list'] = {}
        logging.info("Wish_list session created")

    if 'coustmer_details' not in request.session:
        request.session['coustmer_details'] = {}
        logging.info("coustmer_details session created")

    def validate_gmail_data(gmail_value):

        try:
            gmail_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.com\b'
            if re.fullmatch(gmail_pattern, gmail_value) is None:
                return False
            return True
        except Exception as e:
            logging.error(f"{e}")

    def validate_contact_data(contact_value):
        try:
            contact_pattern = r'\b[0-9]+\b'
            if len(contact_value) == 10:
                if re.fullmatch(contact_pattern, contact_value) is None:
                    return False
                else:
                    if contact_value[0] in ['6', '7', '8', '9']:
                        return True
                    return False
            return False
        except Exception as e:
            logging.error(f"{e}")
    if request.method == 'POST':
        user_email = request.POST.get('user_email')
        contact_number = request.POST.get('contact_number')
        if validate_contact_data(contact_number) and \
                validate_gmail_data(user_email):
            india_time = fetch_date_time()
            signup = UserDetails()
            signup.user_email = user_email
            signup.contact_number = contact_number
            signup.created = india_time
            signup.updated = india_time
            signup.save()
            categories = Menu.objects.all()
            cart = request.session.get('cart')
            keys = [key for key in cart.keys()]
            list_quantity = FoodItem.objects.filter(name__in=keys)
            coustmer_details = request.session.get('coustmer_details')
            coustmer_details['contact_number'] = contact_number
            coustmer_details['date'] = india_time
            request.session['coustmer_details'] = coustmer_details
            logging.info("After sginup render to Menu page")
            return render(request,
                          'main_menu.html',
                          {'categories': categories,
                           'list_quantity': list_quantity})
        else:
            messages.error(request,
                           'Please enter valid email or contact number')
            logging.error("Please enter valid email or contact number")
            return redirect(reverse('menu:signup'))

    else:
        return render(request, 'signup.html')
        # return redirect(reverse('menu:signup'))


def menu_list(request):
    """
    This method display list of all food category on menu page
    and based on your select category, it will go category details page.

    """
    categories = Menu.objects.all()
    cart = request.session.get('cart')
    logging.info("Back to Menu page")
    keys = [key for key in cart.keys()]
    list_quantity = FoodItem.objects.filter(name__in=keys)
    return render(request,
                  'main_menu.html',
                  {'categories': categories,
                   'list_quantity': list_quantity})


def food_items_details(request, id, menu_slug):
    """
    This method display selected category food details on menu page

    cart: if you click on cart button food will store in cart session
        if you click on + button, selected food quantity increase by 1 in cart
        if you click on - button, selected food quantity decrease by 1 in cart

    wishlist: if you click on wishlist button
                food will store in wishlist session.

    """
    category = get_object_or_404(Menu, id=id)
    logging.info(f"Selected {menu_slug}")
    if request.method == 'POST':
        # Process the form data
        wish_list = request.session.get('wish_list')
        cart = request.session.get('cart')
        product = request.POST.get('product')
        remove = request.POST.get('remove')
        quantity = request.POST.get('quantity')
        food_wish_list = request.POST.get('food_wish_list')
        product = product.split('-')
        if food_wish_list != 'this is wish':
            quantity = cart.get(product[1])
            if quantity:
                if remove:
                    if quantity <= 1:
                        cart.pop(product[1])
                        logging.info(f"{product[1]} removed from cart")
                    else:
                        cart[product[1]] = quantity - 1
                        logging.info(
                            f"{product[1]} decreased one quantity from cart")
                else:
                    cart[product[1]] = quantity + 1
                    logging.info(
                        f"{product[1]} increased one quantity in cart")
            else:
                cart[product[1]] = 1
                logging.info(f"{product[1]} added to cart")
        else:
            wish_list[product[0]] = 1
            logging.info(f"{product[0]} added to wishlist")

        request.session['wish_list'] = wish_list
        request.session['cart'] = cart
        cart = request.session.get('cart')

        # Redirect to the same view using the reverse function
        return redirect(reverse(
            'menu:food_items_details',
            kwargs={'id': id, 'menu_slug': menu_slug}))

    cart = request.session.get('cart')
    keys = [key for key in cart.keys()]
    list_quantity = FoodItem.objects.filter(name__in=keys)
    food_details_list = FoodItem.objects.filter(category_id=str(id))
    return render(request,
                  'food_details.html',
                  {'food_details_list': food_details_list,
                   'category': category,
                   'list_quantity': list_quantity})


def cart(request):
    """
    This method display all food details which are store in cart.

    if you click on + button, selected food quantity increase by 1 in cart
    if you click on - button, selected food quantity decrease by 1 in cart

    """
    logging.info("Cart page fetched")
    cart = request.session.get('cart')

    if request.method == 'POST':
        product = request.POST.get('product')
        remove = request.POST.get('remove')
        quantity = request.POST.get('quantity')
        product = product.split('-')
        quantity = cart.get(product[1])
        if quantity:
            if remove:
                if quantity <= 1:
                    cart.pop(product[1])
                    logging.info(f"{product[1]} removed from cart")
                else:
                    cart[product[1]] = quantity-1
                    logging.info(
                        f"{product[1]} decreased one quantity from cart")
            else:
                cart[product[1]] = quantity+1
                logging.info(f"{product[1]} increased one quantity in cart")
        else:
            cart[product[1]] = 1

        request.session['cart'] = cart
        return redirect(reverse('menu:cart'))

    cart = request.session.get('cart')
    keys = [key for key in cart.keys()]
    food_details_list = FoodItem.objects.filter(name__in=keys)
    return render(request,
                  'cart.html',
                  {'food_details_list': food_details_list})


def wishlist(request):
    """
    This method display all food details which are store in wishlist.

    if you click on add to cart button:
        selected food will store in cart and default quantity as 1

    """
    logging.info("wishlist page fetched")
    wish_list = request.session.get('wish_list')
    cart = request.session.get('cart')

    if request.method == 'POST':
        product = request.POST.get('product')
        product = product.split('-')
        print('product is:', product)
        logging.info(f"{product[1]} added to cart from wishlist")
        wish_list.pop(product[0])
        cart[product[1]] = 1
        request.session['wish_list'] = wish_list
        request.session['cart'] = cart

    wish_list = request.session.get('wish_list')
    keys = [int(key) for key in wish_list.keys()]
    food_details_list = FoodItem.objects.filter(id__in=keys)
    return render(request,
                  'wishlist.html',
                  {'food_details_list': food_details_list})


def checkout(request):
    """
    This method display food status to user.

    if food status in DB is pending:
        status is food is preparing
    else:
        food is ready
    """
    logging.info("Checkout page fetched")
    cart = request.session.get('cart')
    coustmer_details = request.session.get('coustmer_details')
    if request.method == 'POST':
        india_time = fetch_date_time()
        cart = request.session.get('cart')

menu/templates/cart.html
{% load static %}

{% load cart %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TableTap Cart</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 20px;
      background-color: #66a8ba;
      background-repeat: no-repeat;
      background-size: cover;
    }
    
    h1 {
      text-align: center;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }
    
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    
    th {
      background-color: #f2f2f2;
    }
    
    .btn {
      display: inline-block;
      padding: 10px 20px;
      background-color: #4CAF50;
      color: #fff;
      text-decoration: none;
      border-radius: 4px;
      transition: background-color 0.3s;
    }
    
    .btn:hover {
      background-color: #45a049;
    }
    
    .quantity-container {
      display: flex;
      align-items: center;
    }
    
    .quantity {
      display: inline-block;
      padding: 5px 10px;
      background-color: #007bff;
      color: #fff;
      text-decoration: none;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s;
    }
    
    .quantity:hover {
      background-color: #0069d9;
    }
  </style>
</head>
<body>
  <h1>Cart</h1>
  
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
        <th></th>
      </tr>
    </thead>
    
    <tbody>

      {% for food in food_details_list %}
      <tr>
        <td><img src="{% if food.image %}{{ food.image.url }}{% else %}{% static " img/no_image.png" %}{% endif %}"
          width="50px" height="50px" border-radus="50%" style="border-radius: 15%">
        <p>{{food.name}}</p></td>
        <td>
          ₹{{food.price}}
        </td>
        <td>

          <form id='form1' action="/cart/" method="POST" style="display: inline;">
            {% csrf_token %}
            <input hidden type="text" name="product" value='{{food.id}}-{{food.name}}'>
            <input hidden type="number" name="remove" value='-1'>
            <button style="width: auto; background-color: red; color: white;">-</button>
        </form>


        {{food|food_quantity:request.session.cart}}

        <form action="/cart/" method="POST" style="display: inline;">
            {% csrf_token %}
            <input hidden type="text" name="product" value='{{food.id}}-{{food.name}}'>
            <button style="width: auto; background-color: green; color: white;">+</button>
        </form>

        </td>
        <td>
          ₹{{food|food_quantity_price:request.session.cart}}
        </td>
      </tr>
      {% endfor %}
      
  
    <tfoot>
      <tr>
        <td colspan="2"><strong>Total:</strong></td>
        <td>{{food_details_list|cart_total_quantity:request.session.cart}}</td>
        <td>₹{{food_details_list|cart_total_price:request.session.cart}}</td>
        
      </tr>
    </tfoot>
  </table>
  
  <a href="{% url 'menu:menu_list' %}" class="btn">Continue Menu</a>
  <form action="/checkout/" method="POST" style="display: inline;">
    {% csrf_token %}
    <input hidden type="text" name="product" value='{{food.id}}'>
    <!-- <input type="submit" value="Checkout"> -->
    <button style=" background-color: #4CAF50; color: white;  width: 100px; height: 38px; border: none; padding-right: 10px;">Checkout</button>

</form>
  
</body>
</html>

menu/templates/checkout.html
{% load static %}

{% load cart %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TableTap Checkout</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 20px;
      background-color: #66a8ba;
      background-repeat: no-repeat;
      background-size: cover;
    }
    
    h1 {
      text-align: center;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }
    
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    
    th {
      background-color: #f2f2f2;
    }
    
    .btn {
      display: inline-block;
      padding: 10px 20px;
      background-color: #4CAF50;
      color: #fff;
      text-decoration: none;
      border-radius: 4px;
      transition: background-color 0.3s;
    }
    
    .btn:hover {
      background-color: #45a049;
    }
    
    .quantity-container {
      display: flex;
      align-items: center;
    }
    
    .quantity {
      display: inline-block;
      padding: 5px 10px;
      background-color: #007bff;
      color: #fff;
      text-decoration: none;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s;
    }
    
    .quantity:hover {
      background-color: #0069d9;
    }
  </style>
</head>
<body>
  <h1>Order placed <a href="{% url 'menu:menu_list' %}"
    style="text-align: right; float: right; color: black; text-decoration: none;">Menu</a></h1>
          
          <p>Order Status: {{request.session.coustmer_details|food_status}}</p>
</body>
</html>

menu/templates/food_details.html
{% extends "project_base.html" %}
{% load static %}
{% load cart %}
{% block content %}
<div id="main" class="col-lg-9 mx-auto">
    <h1>{{ category }} <a href="{% url 'menu:menu_list' %}"
            style="text-align: right; float: right; color: black; text-decoration: none;">Menu</a></h1>
    <div class="row">
        {% for food in food_details_list %}
        <div class="col-md-3 mt-4">
            <a>
                <img src="{% if food.image %}{{ food.image.url }}{% else %}{% static " img/no_image.png" %}{% endif %}"
                    width="100%" height="240" border-radus="50%" style="border-radius: 15%">
            </a><br>
            <a
                style="color: black; margin-left: 124px; text-decoration: none;">{{food.name }}</a>
            <!-- <p style="margin-left: 124px;">{{ food.description }}</p> -->
            <p style="margin-left: 124px;">₹{{ food.price }}</p>

            <div class="text-center col">
                {% if food|is_in_cart:request.session.cart %}
                <div>
                    <form id='form3' method="POST" style="display: inline;">
                        {% csrf_token %}
                        <input hidden type="text" name="product" value='{{food.id}}-{{food.name}}'>
                        <input hidden type="number" name="remove" value='-1'>
                        <button style="width: auto; background-color: red; color: white;">-</button>
                    </form>
    
                    {{food|food_quantity:request.session.cart}}
    
                    <form id='form4' method="POST" style="display: inline;">
                        {% csrf_token %}
                        <input hidden type="text" name="product" value='{{food.id}}-{{food.name}}'>
                        <button style="width: auto; background-color: #4CAF50; color: white;">+</button>
                    </form>
                </div>
                {% else %}
                <div>
                    <form id='form1' method="POST" style="margin-bottom: 20px; display: inline;">
                        {% csrf_token %}
                        <input hidden type="text" name="product" value='{{food.id}}-{{food.name}}'>
                        <button style="width: auto; background-color: black;">&#x1F6D2;</button>
                    </form>

                    <form id='form2' method="POST" style="display: inline;">
                        {% csrf_token %}
                        <input hidden type="text" name="product" value='{{food.id}}'>
                        <input hidden type="text" name="food_wish_list" value='this is wish'>
                        <button style="width: auto;">&#x1F496;</button>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

menu/templates/main_menu.html
{% extends "project_base.html" %}
{% load static %}
{% block content %}
 <div id="main">
 <h1>Menu</h1>
 <div class="row">
    {% for product in categories %}
    <div class="col-md-3 mt-4">
    <!-- <div class="col-md-12 mt-1"> -->
    <a href="{% url 'menu:food_items_details' id=product.id menu_slug=product.slug %}">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" width="100%" height="240" border-radus="50%" style="border-radius: 15%">
    </a>
    <br>
    <a href="{% url 'menu:food_items_details' id=product.id menu_slug=product.slug %}" style="color: black; margin-left: 124px; text-decoration: none;">{{ product.name }}</a>
    </div>
    {% endfor %}
    
 </div>

 </div>
{% endblock %}

menu/templates/project_base.html
{% load static %}
{% load cart %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="utf-8" />
 <title>{% block title %}TableTap{% endblock %}</title>
 <link href="{% static "css/project_base.css" %}" rel="stylesheet">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
  <style>
    .cart-emoji,

.wishlist-emoji {

    font-size: 20px;

    cursor: pointer;

    position: absolute;

    top: 20px;

    right: 20px;

}


.cart-emoji {

    right: 60px;

}

.wishlist-emoji {

    right: 20px;

}
  </style>
 </head>
 <body style="background-color:orange;">
 <div id="header">
 <a href="/" class="logo" style="text-decoration: none; margin-left: 143px">TableTap</a>


 <!-- <a href="/wishlist/" style=" margin-right: 48px; color: black; text-decoration: none; float: right"><img class="cart_imge" src="/static/images/wishlist.jfif"  width=50px height=50px></a>
 <a href="/cart/" style=" margin-right: 48px; color: black; text-decoration: none; float: right"><img class="cart_imge" src="/static/images/cart.png"  width=50px height=50px> <span>{{0}}</span></a> -->

<span class="cart-emoji" onclick="window.location.href='/cart'" style="float: right; margin-right: 122px">&#x1F6D2;{{list_quantity|cart_total_quantity:request.session.cart}}</span>

<span class="wishlist-emoji" onclick="window.location.href='/wishlist'" style="float: right; margin-right: 130px">&#x1F496;</span>

 </div>
 <!-- <div id="subheader">
 <div class="cart">
 {% with total_items=cart|length %}
 {% if total_items > 0 %}
 <a href="cart.html"><img src="C:/Users/VinodKumar/Desktop/table tap/TableTap/menu/static/cart.png"></a> -->
 Your cart:
<a href="{% url "cart:cart_detail" %}">
{{ total_items }} item{{ total_items|pluralize }},
${{ cart.get_total_price }}
</a>
 {% elif not order %}
 <a href="cart.html"><img class="cart_imge" src="static/cart.png"  width=50px height=50px></a>
 <!-- Your cart is empty. -->
 {% endif %}
 {% endwith %}
 </div>
 </div>
 <div id="content">
 {% block content %}
 {% endblock %}
 </div>
 </body>
</html>

menu/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  {% if messages %}
  {% for message in messages %}
    <div class="alert {{ message.tags }} m-2" id="msg" role="alret">
      {{message}}
    </div>
  {% endfor %}
{% endif %}
  <title>Signup</title>
</head>
<body>
  <h1>signup</h1><br><br>
  <form method="POST">
    {% csrf_token %}
    <input type="text" name="user_email" placeholder="Enter email" required><br>
    <input type="text" name="contact_number" placeholder=" Enter Contact Number" required><br><br>
    <button type="submit">submit</button>
</form>
</body>
</html>

menu/templates/wishlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TableTap Wishlist</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 20px;
      background-color: #66a8ba;
      background-repeat: no-repeat;
      background-size: cover;
    }

    h1 {
      text-align: center;
      color: #333;
      margin-bottom: 40px;
    }

    .wishlist-container {
      max-width: 800px;
      margin: 0 auto;
      background-color: rgba(255, 255, 255, 0.9);
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .wishlist-item {
      display: flex;
      align-items: center;
      margin-bottom: 20px;
      padding: 15px;
      border-radius: 5px;
      background-color: #f9f9f9;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .wishlist-item img {
      width: 80px;
      height: 80px;
      object-fit: cover;
      margin-right: 20px;
      border-radius: 5px;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .wishlist-item .item-details {
      flex-grow: 1;
    }

    .wishlist-item h2 {
      margin: 0;
      font-size: 18px;
      color: #333;
      margin-bottom: 10px;
    }

    .wishlist-item p {
      margin: 0;
      color: #666;
      margin-bottom: 5px;
    }

    .wishlist-item button {
      padding: 8px 16px;
      background-color: #333;
      color: #fff;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s;
    }

    .main-menu-button button {
      padding: 8px 16px;
      background-color: black;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      /* transition: background-color 0.3s; */
    }
    
    .wishlist-item button:hover {
      background-color: #555;
    }
  </style>
</head>

<body>
  <h1>My Wishlist</h1>
  <div class="wishlist-container">
    {% for food in food_details_list %}
    <div class="wishlist-item">
      <img src="{% if food.image %}{{ food.image.url }}{% else %}{% static " img/no_image.png" %}{% endif %}"
          width="50px" height="50px" border-radus="50%" style="border-radius: 15%">
      <div class="item-details">
        <h2>{{food.name}}</h2>
        <p>Price: {{food.price}}</p>
        <p>Description: {{food.description}}</p>
      </div>

      <form action="/wishlist/" method="POST">
        {% csrf_token %}
        <input hidden type="text" name="product" value='{{food.id}}-{{food.name}}'>
        <input type="submit" value="Add to Cart">
      </form>

    </div>

    {% endfor %}

    <div class="main-menu-button">
      <a  href="{% url 'menu:menu_list' %}" class="btn"><button>Continue Menu</button></a>
    </div>
    
    <!-- <button>Continue Menu</button> -->
  </div>
   